messageformat/messageformat

- .gitignore
- .travis.yml
- LICENSE
- Makefile
- bin/messageformat.js
- example/en/i18n.js
- example/fr/i18n.js
- jsdoc-conf.json
- lib/messageformat.dev.js
- messageformat.js
- package.json
Working towards better documentation, I added [JSDoc](http://usejsdoc.org/) commentary throughout the source. In addition to being readable _in situ_, it compiles to HTML pretty cleanly.
While at it, I cleaned up the source in a couple of places, most visibly moving `mparser = require('./message_parser')` to be within `MessageFormat._parse`, and removing the `_` prefixes of the runtime functions.
This could be left as is, or we could add `jsdoc` as a dependency, along with a suitable config file and a `make` rule. Here's the minimal `conf.json` I've been using so far:
```json
{
"source": { "include": [ "lib/messageformat.dev.js" ] },
"plugins": [ "plugins/markdown" ]
}
```
Regarding the copyright statement, I went for now with "2012-2015 Alex Sexton and other contributors". Is that all …
> Add JSDoc comments to source

- lib/message_parser.pegjs
- lib/messageformat.dev.js
- messageformat.js
- test/tests.js
I am currently getting started with MessageFormat and as a starting point I was reading your definition of the MessageFormat grammar.
Doing so, I noticed some minor things which could be done to simplify the pegjs grammar:
* PegJS grammar:
* Remove `messageFormatPatternRight` and directly use `messageFormatElement` within `messageFormatPattern`
* Remove `pluralStyle` and `selectStyle` which were just forwarding to `pluralFormatPattern` respectively `selectFormatPattern`
* simplified parsing of strings and ids
* automatically compile the grammar in the development version
* I added two new testcases for trailing and leading whitespace in strings
All testcases are passing for messageformat.js and lib/messageformat.dev.js
> Parser improvements

- test/tests.js
I added 3 regression tests for #92. They are using Messageformat strings like
```
{VAR, select,
a{correct}
other {b {VAR, spy}}
other {incorrect {VAR, spy}}
}
```
where `spy` is a runtime function. The MessageFormat string is called with `VAR = "a"` and the test case fails if the `spy` function was called. I wrote three variations of this test case. One for each of `select`, `plural` and `selectordinal`.
> added regression tests for #92

- lib/messageformat.js
- test/tests.js
I used `JSON.stringify` to escape special characters instead of a do-it-yourself solution.
> Fixes #99: Code injection using \u005c

- lib/messageformat-parser.pegjs
- lib/messageformat.js
- test/tests.js
While fixing #99, I noticed that there is no escape sequence for the backslash itself.
The last commit of this pull request introduces the escape sequence `\\`.
The first two commits are already part of pull request #100 but I included them here as well since an escape sequence for backslashes without properly escaping backslashes in the output is a bad idea.
> Escape sequence for a literal backslash

- lib/messageformat-parser.pegjs
- lib/messageformat.js
**The first commit** (7bd124b) contains some minor parser changes:
* simplified the messageFormatPattern rule
* renamed rules: `pluralForms` -> `pluralForm`, `selectForms` -> `selectForm`.
I prefer the singular since these rules match only one pluralForm / selectForm
* do not accept plural/selectFormatPatterns with 0 plural/selectForms
**The second commit** (250ec41) replaces replaces the current RegExp solution for parsing # placeholders by a PEG.js parser rule.
Pros:
* all parsing is done in the _parse method.
* I consider a PEG.js grammar to be more secure against injections than handcrafted regular expressions (although I don't know about a possible injection with the current RegExp solution)
Cons:
* The generated code for `an octothorpe: #` now looks like `"an octothorpe: " + "#"` …
> Various small parser improvements

- package.json
So as to avoid webpack warnings being thrown when compiling an app with messageformat in, we need to specify a browser definition for fs.
From the creator of weback to jade:
https://github.com/jadejs/jade/pull/1644
> Package.json - Added browser config for fs

- Makefile
- README.md
- bower.json
- example/en/i18n.js
- example/en/sub/folder/plural.json
- example/fr/i18n.js
- example/fr/sub/folder/plural.json
- example/index.html
- jsdoc-fix-fonts.patch
- package.json
I finally got around to doing something about the documentation, and ended up with [messageformat.github.io](http://messageformat.github.io/) ([source repo](https://github.com/messageformat/messageformat.github.io)), which now has what used to be in README.md + the JSDoc output. I've removed here the pre-compiling sections and MarkDown guide from the README and updated the rest, referring to the site for more info.
With this, I think we could finally release 0.3.0. @SlexAxton, what do you think?
> Update readme & homepage

- lib/messageformat.js
- test/tests.js
When compiled objects use JavaScript reserved words as keys they are not being enclosed in quotes which causes errors in IE <= 8. This change corrects the problem.
In this example the JavaScript reserved word `default` is used as a key.
```
var messages = {
default: "IE <= 8 can't load the compiled script because 'default' is a reserved word in JavaScript"
}
var MessageFormat = require('messageformat');
var messageformat = new MessageFormat();
var compiled = messageformat.compile(messages);
compiled.toString();
```
```
function anonymous() {
var number = function (value, offset) {
if (isNaN(value)) throw new Error("'" + value + "' isn't a number.");
return value - (offset || 0);
};
var plural = function (value, offset, lcfunc, data, isOrdinal) {
if ({}.hasOwnProperty.call(data, value)) …
```
> Enclose JavaScript reserved words used as keys in quotes

- component.json
We should deprecate support for component, as it [is no longer maintained](/componentjs/component/issues/639). Also, I at least wasn't able to find messageformat on [component.github.io](http://component.github.io/), and component.io appears to longer be operational.
> Remove component.json

- package.json
A dep of watchr is causing installs to fail, as per https://github.com/bevry/typechecker/issues/13
I've released v2.5.0 of watchr, so this will need to be updated. Watchr follows semver, so changed ~ to ^
> Update watchr dep

- lib/compiler.js
- lib/index.js
- test/messageformat.js
Removed in a005b99561012510885cca61ba89864af83d9c3b
> Restore better error message for missing argument referenced with '#' in plural rule

- Makefile
- doc/jsdoc-conf.json
- lib/index.js
- lib/runtime.js
- test/messageformat.js
This relaxes the default runtime treatment of `#`, and expands the meaning of  `MessageFormat#setStrictNumberSign(true)` to return to the previous, stricter treatment.
Before, we had this:
```js
var mf = new MessageFormat('en');
var msg = '{X, plural, one{the thing} other{# things}}';
mf.compile(msg)({ X: 3 });
// '3 things'
mf.compile(msg)({ X: 'cool' });
// Error: 'cool' from argument 'X' isn't a number.
```
With this PR, we get this:
```js
var mf = new MessageFormat('en');
var msg = '{X, plural, one{the thing} other{# things}}';
mf.compile(msg)({ X: 3 });
// '3 things'
mf.compile(msg)({ X: 'cool' });
// 'cool things'
mf.compile(msg)({});
// 'undefined things'
mf.setStrictNumberSign(true);
mf.compile(msg)({ X: 'cool' });
// Error: Argument `X` has non-numerical value "cool".
```
To get …
> Throw fewer runtime errors for `#`

- .travis.yml
- lib/compiler.js
- lib/index.js
- test/messageformat.js
According to the spec, all `plural`, `select`, and `selectordinal` instances should include an `other` case as a fallback. If, however, messageformat has been initialised with a custom pluralisation function (i.e. with `new MessageFormat({ [lc]: function })`), that function (and therefore the string being parsed) may use a different set of pluralisation categories than the standard zero/one/two/few/many/other. Therefore in that case we should trust that the user knows what they're doing, and not complain about the missing key.
This is relevant to my interests as I'm working on [gettext-to-messageformat](/eemeli/gettext-to-messageformat), and gettext uses language-specific integers for pluralisation categories, along with  an inline-provided pluralisation function.
> Don't require `other` in plurals when plural functions have been set manually

- .travis.yml
As I mentioned [here](/messageformat/messageformat.js/issues/173#issuecomment-345417791):
> Our API docs are being built by jsdoc, which needed to get updated to work with node 8.5 because of jsdoc3/jsdoc#1438, but on the other hand that's now depending on babel 7.0, which dropped support for node 0.12 with babel/babel#4315.
So we need to update at least our Travis CI config in order to get any CI tests to pass. Node v4 is the oldest which should work fine; Node v6 currently has the highest number of users.
> Update Travis CI config: Drop v0.10, v0.12 & iojs, add v4 & v6

- bin/messageformat.js
See #165 for the discussion leading to this. This PR adds a `--simplify` command-line parameter to `bin/messageformat.js`:
```
-s, --simplify
Simplify the output object structure, by dropping intermediate keys when
those keys are shared across all objects at that level, in addition to
the default filtering-out of shared keys at the root of the object.
[default: false]
```
Sorry, this has been sitting on my private branch for ages now, completely forgot that it probably ought to be merged into upstream as well...
> Add --simplify option to bin/messageformat

- Makefile
- lib/get.js
- test/get.js
Re: #187, possibly some other issues as well.
This adds `lib/get.js`, a runtime accessor class for compiled MessageFormat objects. It's a new API, so the method and other names can and should be changed if we think of something else that's better. Here's how it would work:
First, presuming that we have the messages in a JSON file `messages.json`:
```json
{
"en": {
"a": "A {TYPE} example.",
"b": "This has {COUNT, plural, one{one user} other{# users}}.",
"c": {
"d": "We have {P, number, percent} code coverage."
}
},
"fi": {
"b": "Tällä on {COUNT, plural, one{yksi käyttäjä} other{# käyttäjää}}.",
"e": "Minä puhun vain suomea."
}
}
```
And that we've compiled that into JavaScript:
```
messageformat -l en,fi messages.json > messageData.js
```
Then we can use the new getter and this API:
```js …
```
> Add runtime accessor class

- index.d.ts
- lib/messageformat.js
With this proposal it should be possible to import this package in typescript projects using require or es6 module style
``` typescript
// old way with require
import MessageFormat = require('messageformat');
// new way with import from syntax
import * as MessageFormat from 'messageformat';
// cleanest way, that needed adjustment in messageformat.js
import { MessageFormat } from 'messageformat';
```
The last version needed a change in the javascript file and was not possible only changing the types definition. Therefore I nested MessageFormat in itself
```javascript
// lib/messageformat.js
MessageFormat.MessageFormat = MessageFormat;
module.exports = MessageFormat;
```
> es6 style imports for typescript

- index.d.ts
MessageFormat's `compile` method returns a function with the native `toString` method [overwritten with a custom implementation](https://github.com/messageformat/messageformat/blob/b563d80/lib/messageformat.js#L354-L368), having an optional `global` parameter to output code depending on the environment.
This PR adds the custom `toString` method to the TypeScript type definitions, avoiding
```
Expected 0 arguments, but got 1.
``` 
errors when calling it with an argument, since the native method signature has no parameters.
> Add TypeScript definition for `toString` with optional `global` argument

- index.d.ts
Adding the type definitions is much appreciated - I've previously included them myself. However, this actually broke my build because the constructor is overloaded instead of using a union type for the parameter. Even though the proposed change doesn't make a semantic difference, here's the problem:
```ts
function(foo: string | string[]) {
new MessageFormat(foo);
}
```
This currently makes the compiler complain (`Argument of type 'string | string[]' is not assignable to parameter of type 'string'. Type 'string[]' is not assignable to type 'string'.`) but works fine with the proposed change.
The underlying reason is that the Typescript compiler doesn't fully deal with calling an overloaded function with a union type argument, see https://github.com/Microsoft/TypeScript/issues/1805.
> Use type union parameter for MessageFormat constructor

- docs/lib_compiler.js.html
- package.json
- packages/messageformat/lib/compiler.js
- packages/messageformat/package-lock.json
- packages/messageformat/package.json
- test/formatters.js
This would fix #201, but requires messageformat/parser#8 before it'll work -- see there for more details.
For testing, use `npm link` from the parser's `function-args` branch and then `npm link messageformat-parser` here to get the appropriate version.
> Allow MessageFormat content in function parameters

- packages/loader/README.md
- packages/loader/index.js
- packages/loader/package.json
This adds a new default-false `convert` option, which allows using non-MessageFormat input as a data source by first converting said input into MessageFormat. With the default options it handles the format used by [Rails i18n](https://guides.rubyonrails.org/i18n.html), but it's configurable for other formats as well.
This is a feature of `messageformat-yaml-loader`, and a part of its merge into `messageformat-loader`.
`messageformat-convert` is atm only available in this repo, but it'll get published on npm  pretty soon.
> feat(loader): Add convert option, using messageformat-convert

- packages/messageformat/index.d.ts
- packages/messageformat/src/compiler.js
- packages/messageformat/src/messageformat.js
- packages/messageformat/src/plurals.js
- packages/messageformat/src/runtime.js
- packages/messageformat/src/utils.js
- test/formatters.js
- test/messageformat.js
This adds a more JavaScript-ish way of configuring a MessageFormat instance, by adding a second options argument to the constructor. Its keys correspond pretty closely to the `addFormatters`, `disablePluralKeyChecks`, `setBiDiSupport`, and `setStrictNumberSign` methods.
The main purpose of this approach is to provide a bridge towards the work I've started in the [`next`](../tree/next) branch, where all of those methods are removed and other potentially breaking changes are helping to simplify the codebase.
> Add a second options argument for the MessageFormat constructor

- packages/messageformat/src/compiler.js
- packages/messageformat/src/runtime.js
- test/messageformat.js
Fixes #246 
BREAKING CHANGE: Previously, non-numeric values used as plural arguments could be referred to using `#` while keeping their original value. With this change, they now get converted to numbers and then formatted, probably coming out as `"NaN"` instead.
The number formatter relies on Intl.NumberFormat being available, and caches its instances.
> Always format # in plurals as number

- packages/messageformat/src/compiler.js
- packages/messageformat/src/messageformat.js
- test/messageformat.js
Fixes #241 
This adds a new method `MessageFormat#setArrayOutput()`, which makes compiled functions return arrays instead of strings, allowing for variable values to not be stringified. Some examples:
```js
const mf = new MessageFormat('en').setArrayOutput()
mf.compile('simple message')()
// ['simple message']
const obj = { foo: 'bar' }
mf.compile('objectively, {obj} is an object')({ obj })
// ['objectively, ', obj, ' is an object']
mf.compile('select {num, plural, one{one} other{#}}')({ num: 42 })
// ['select ', [42]]
> Add option for array output

- packages/messages/src/messages.js
The default locale was not set correctly due to a missing underscore (this was also the case with the js version of this file). I've also removed the double export, as that resulted in a "Cannot access 'Messages' before initialization", which seems logical.
> Fixed typo when setting default locale, removed double export

- packages/runtime/messages.d.ts
As requested in #255 by @eemeli , the typing I created as PR for the current master branch. 
If you expect them to have a different layout (maybe you want the comments stripped here?), let me know.
> Added typings for messageformat-runtime/messages

- packages/messageformat/src/compiler.js
- packages/messageformat/src/messageformat.js
- packages/runtime/src/runtime.mjs
- test/messageformat.js
Fixes #193 
This adds an option `requireAllArguments` to `new MessageFormat` that checks during runtime that each message function that's called with parameters has some defined values for those parameters:
```js
const mf = new MessageFormat('en', { requireAllArguments: true })
const msg = mf.compile('This is {foo}')
const data = { bar: 'BAR' }
msg(data) // throws Error: "Message requires argument 'foo'"
```
The check that's made in e.g. the above case is `!!data && data.foo === undefined`, so using `{ foo: null }` would not throw.
I would welcome comments on the option name, the check that's used, and the general approach that's used here. Also important to note: As is, all of the parameters are required, even if they're in cases not used by the current message. In other words, this too …
> Add requireAllArguments option to compiler

- CONTRIBUTING.md
The previous link [`https://js.foundation/CLA/`](https://js.foundation/CLA/) no longer provides information about CLA agreement/signing
> fix(contributing): use direct link to license agreement to messageformat

- package-lock.json
- packages/messageformat/package.json
- packages/messageformat/src/compiler.js
- test/formatters.js
This adds support for [date skeletons](http://userguide.icu-project.org/formatparse/datetime), much like #272 did for numbers. Date patterns aren't supported, because they can't really be worked with Intl.DateTimeFormat. The skeletons work like this:
```js
const mf = new MessageFormat('en')
// 2006 Jan 2, 15:04:05.789 in local time
const example = new Date(2006, 0, 2, 15, 4, 5, 789);
const msg1 = mf.compile('{example, date, ::GGGGyMMMM}')
msg1({ example })
// 'January 2006 Anno Domini'
const msg2 = mf.compile('{example, date, ::hamszzzz}')
msg2({ example })
// '3:04:05 PM Eastern European Standard Time'
```
Internally this makes use of new package, `messageformat-date-skeleton`. The skeletons are now both in a second monorepo, [messageformat/skeletons](https://github.com/messageformat/skel …
> feat(messageformat): Add support for date skeletons

- README.md
Note: I'm not sure if this is supposed to be `@messageformat/rollup-plugin` -- I did it this way to match the [top-level package.json](https://github.com/messageformat/messageformat/blob/df713b1714837b92e2bf4c07d5323c21c78df278/package.json#L41-L52)
Also definitely squash merge to remove all my intermediate commits -- I was using the online GitHub editor and couldn't find an amend button :)
> Add `rollup-plugin-messageformat` to README's list of packages

- packages/runtime/esm/package.json
Fixes #303 
Closes #305
Ping @gamedevdan
In testing, I was able to duplicate the original reported issue with Webpack 5 and resolve it by adding the missing `esm/package.json` file that correctly identifies files within that folder as using ES rather than CommonJS modules.
Given that this should also enable `@messageformat/runtime/esm/...` content to be used in Node.js environments, it's much preferable to the alternative of removing the `"type"` from the module's root package.json file.
> fix(runtime): Add missing esm/package.json

- packages/core/src/compiler.ts
- packages/react/src/__fixtures__/messages_en.js
- packages/react/src/__fixtures__/messages_fi.js
- packages/react/src/examples.test.tsx
- packages/rollup-plugin/README.md
- packages/rollup-plugin/src/__snapshots__/rollup.test.ts.snap
- packages/rollup-plugin/src/index.test.ts
This changes the JS representation of compiled messages as follows:
```
A simple message.
was: function(d) { return "A simple message."; }
now: () => "A simple message."
```
```
Message with {X}.
was: function(d) { return "Message with " + d.X + "."; }
now: (d) => "Message with " + d.X + "."
```
In addition to using a terser expression of the function, the `d` argument is left out when not used. Therefore it becomes possible to use the function's `length` property to determine if it requires at least some argument.
Using a template literal instead of + for concatenation would only save an additional single character, so it's probably not worth the complexity that it would introduce.
> Use fat-arrow notation for message functions

- package-lock.json
- package.json
- test/browser/src/browser-tests.ts
- test/browser/src/ie11-polyfills.js
- test/browser/test.html
- test/browser/tests/ie.js
- test/fixtures/formatters.ts
- test/fixtures/messageformat.ts
- test/rollup.config.js
With the change made in #309, the generated message modules would need to be transpiled by e.g. Babel for IE 11 support.
There's no reason to expect that to still work, but it's a hassle to maintain support for such an obsolete browser with limited `Intl` support. So let's not. This also lets us get rid of the polyfills required by IE 11.
The current/remaining minimum browser versions against which the full test suite is run includes:
- Chrome 78
- Edge 18
- Firefox 71
- Safari 12.1
That is of course in addition to running the tests against Node.js 10, 12 & 14.
> Drop IE 11 testing & explicit support

- packages/core/src/compile-module.test.ts
- packages/core/src/compile-module.ts
- packages/core/src/compiler.ts
- packages/core/src/messageformat.test.ts
- packages/core/src/messageformat.ts
- packages/number-skeleton/src/errors.ts
- packages/react/src/get-message.ts
- packages/react/src/message-context.ts
- packages/react/src/message-provider.ts
- packages/react/src/message.ts
- packages/react/src/use-message.ts
- packages/runtime/src/messages.ts
- packages/runtime/src/runtime.ts
- test/browser/src/browser-tests.ts
- test/fixtures/messageformat.ts
Fixes #307 by using TS generics to specify the message function return type.
I was actually a bit surprised that this turned out to work in an actually type-safe fashion; there's now a `ReturnType` generic type on the MessageFormat class that defaults to `'string'`, but if the constructor gets called with an options object that includes `returnType: 'values'`, then that toggles the type as well, and that's then used to type the message function return type.
This PR also gets rid of most `any` typings, hopefully without causing any problems to external users.
> Improve TypeScript types

- packages/core/src/compiler.ts
- packages/core/src/messageformat.ts
- test/fixtures/messageformat.ts
This follows from an earlier [similar change](http://messageformat.github.io/messageformat/api/parser.parseoptions.strict/) made to the parser.
The actual behaviour of the option is not changed; previously setting `strictNumberSign: true` was in fact also disabling custom formatters.
Fallback handling in the MessageFormat constructor will allow previous users of the option to be unaffected at least for now, even though this is not documented.
> feat(core): Rename "strictNumberSign" option as "strict"

- docs/custom-formatters.md
- examples/custom-formatter/README.md
- examples/custom-formatter/number.js
- examples/custom-formatter/package.json
- examples/custom-formatter/rollup.config.js
- examples/custom-formatter/src/main.js
- examples/custom-formatter/src/messages.properties
- package-lock.json
- package.json
- packages/core/src/compile-module.test.ts
- packages/core/src/compile-module.ts
- packages/core/src/compiler.ts
- packages/core/src/messageformat.ts
- packages/rollup-plugin/src/index.test.ts
Closes #229 
This effectively provides a way for custom formatters to be made reusable, and e.g. published as npm modules. To do that, we add an object form to the values that may be passed to `options.customFormatters`.
As an example, if we had this module available:
```js
// number.js
export function number(value, locale, options = {}) {
const nf = new Intl.NumberFormat(locale, options);
return nf.format(value);
}
```
We could use it like this:
```js
// rollup.config.js
import alias from '@rollup/plugin-alias';
import messageformat from 'rollup-plugin-messageformat';
import { number } from './number';
export default {
input: 'src/main.js',
output: { dir: 'dist' },
plugins: [
alias({ entries: { '@number': './number.js' } }),
messageformat({
customFormatters: {
number: { formatter: …
```
> Make custom formatters importable + shape their args

- packages/react/src/message-provider.ts
The `@messageformat/react` package `MessageProvider` prop `pathSep` types only allow `string` and `undefined` values, while the documentation states that `null` is also a valid value. This fixes the issue by adding the missing type.
> Fix pathSep types

- .github/workflows/nodejs.yml
- packages/core/src/messageformat.test.ts
- test/fixtures/formatters.ts
BREAKING CHANGE: Tests for the library in Node.js 10 are dropped. No immediate changes should cause any part of the library not to work with Node.js 10, but that will no longer be verified by CI tests or otherwise.
> Drop Node.js 10 tests/support due to its EOL

- CONTRIBUTING.md
This PR proposes some succinct "heads up / how-to" instructions for using the CLA. It also includes a gentle reminder about joining the Foundation itself, because the people who can sign a CLA and the people who can sign a membership agreement are likely the same people. :-)
Please feel free to tweak this language if necessary. This can land at the same time we enable the CLA bot.
Signed-off-by: Brian Warner <brian@bdwarner.com>
> Add EasyCLA instructions

- packages/cli/lib/read-input.js
This is a minimal fix for the clearly-buggy behaviour reported by @cdaringe in #339, where a single top-level key is lost. I think this is a patch-level update, while fixing the general case of the CLI's weird default behaviour would be a breaking change.
> fix(cli): Do not drop initial keys for single-message input files

- packages/runtime/src/runtime.ts
The select function should have a string type for the `value` parameter. Since it cannot be type checked, it doesn't throw any error, except when using the cli's output in ts files.
> Use a string param in the select runtime function

- docs/guide.md
Fixes a small typo in the documentation. `precide -> precise`
> Fix typo in documentation

- packages/number-skeleton/src/skeleton-parser/skeleton-parser.test.ts
- packages/number-skeleton/src/skeleton-parser/token-parser.ts
- packages/number-skeleton/src/types/skeleton.ts
Added the rounding modes `Half Ceiling` and `Half Floor` and `Half Odd`. See [ICU Rounding Modes](https://unicode-org.github.io/icu/userguide/format_parse/numbers/rounding-modes.html)
> feat(number-skeleton): Add rounding-modes Half Ceiling and Half Floor

- packages/cli/lib/read-input.js
Fixes #387
Backward-slashes are replaced with forward-slashes in glob pattern when using `windowsPathsNoEscape: true` option in `glob.sync`. This does mean that symbols cant be escaped in glob patterns but I think it isn't a problem in this use-case.
Did manual testing with windows and mac and both seemed to still work.
> fix(cli): Support Windows paths as directory path inputs

- packages/number-skeleton/src/numberformat/options.test.ts
- packages/number-skeleton/src/numberformat/options.ts
- packages/number-skeleton/src/skeleton-parser/options.ts
- packages/number-skeleton/src/skeleton-parser/skeleton-parser.test.ts
- packages/number-skeleton/src/skeleton-parser/token-parser.ts
- packages/number-skeleton/src/types/skeleton.ts
Add support for skeleton "precision-currency-standard/w"
Issue #391
Example using Node 19:
```bash
> start
> node -i -r ./scripts/start.js
Welcome to Node.js v19.9.0.
Type ".help" for more information.
> mf.compile('{test, number, ::currency/EUR precision-currency-standard/w}')({test: 3.00})
'€3'
> mf.compile('{test, number, ::currency/EUR precision-currency-standard/w}')({test: 3.10})
'€3.10'
> mf.compile('{test, number, ::currency/EUR precision-currency-standard/w}')({test: 3.14})
'€3.14'
> mf.compile('{test, number, ::currency/EUR precision-currency-standard}')({test: 3})
'€3.00'
```
> feat(number-skeleton): Add support for skeleton "precision-currency-standard/w"

- packages/parser/src/parser.test.ts
- packages/parser/src/parser.ts
Issue #393 
As recommended in the issue referenced above, this change introduces a new option to the parser: `strictPluralKeys`, which is set to `true` by default. Relevant unit tests have also been added.
Once the PR is merged and a new version of `@messageformat/parser` released, I'll create a subsequent PR to add support for this option in `@messageformat/core`.
> feat(parser): Introduce new ParseOption to disable strict plural key check

- packages/core/src/compiler.ts
- packages/core/src/messageformat.test.ts
- packages/core/src/messageformat.ts
Issue #393 
As a part of the above mentioned issue, this change adds the `strictPluralKeys` option to the `@messageformat/core` package.
The corresponding option has already been added to `@messageformat/parser` in #397.
> feat(core): Add `strictPluralKeys` option for supporting the corresponding option in parser

- docs/guide.md
CLDR has been moved to a new domain, and the plural rules link at this page https://messageformat.github.io/messageformat/guide/#pluralformat stopped working.
This PR sets the new URL for the "CLDR table of plural rules" link.
> docs(guide): cldr plural rules table at unicode.org

- packages/mf2-messageformat/src/cst/declarations.ts
- packages/mf2-messageformat/src/cst/expression.ts
- packages/mf2-messageformat/src/cst/names.ts
- packages/mf2-messageformat/src/cst/values.ts
- packages/mf2-messageformat/src/data-model/parse.test.ts
- packages/mf2-messageformat/src/data-model/parse.ts
- packages/mf2-messageformat/src/data-model/stringify.ts
- packages/mf2-messageformat/src/index.ts
- packages/mf2-messageformat/src/messageformat.test.ts
- packages/mf2-messageformat/src/messageformat.ts
The spec discussion and probable change in tc39/proposal-intl-messageformat#47 of requiring messages to be input as data models has highlighted the need for a performant parser. That's added here as `parseMessage(source, options)`. Its only supported option is `privateAnnotation`, a function that can be defined to parse private `^` and `&` annotations.
Unlike the CSV parser, this one does not create any intermediate structure on its way to the data model. It's also smaller, minifying & compressing to 2.3kB compared to the CSV's 4.4kB (The MessageFormat runtime is about 4.2kB).
> Add a separate MF2 parser optimised for formatting

- packages/mf2-fluent/src/fluent-to-resource.ts
- packages/mf2-icu-mf1/src/mf1-to-message.ts
- packages/mf2-messageformat/src/data-model/function-annotation.test.ts
- packages/mf2-messageformat/src/data-model/literal.test.ts
- packages/mf2-messageformat/src/data-model/markup.test.ts
- packages/mf2-messageformat/src/data-model/unsupported-annotation.test.ts
- packages/mf2-messageformat/src/data-model/variable.test.ts
- packages/mf2-messageformat/src/messageformat.ts
- packages/mf2-messageformat/src/mf2-features.test.ts
- packages/mf2-messageformat/src/spec.test.ts
This is a breaking change, following the spec change in tc39/proposal-intl-messageformat#62.
Note that as both arguments accept a string value, tooling such as TypeScript may not catch all the places where you'll need to change your code.
This also means that the constructor now has two required arguments, albeit the first one can be `undefined`.
> Flip MF2 constructor args from (source, locales, options) to (locales, source, options)

- packages/mf2-messageformat/src/data-model/stringify.ts
- packages/mf2-messageformat/src/messageformat.ts
This is a breaking change, following the spec change in tc39/proposal-intl-messageformat#63.
> Drop locales & message from MF2 resolvedOptions()

- mf2/fluent/src/fluent.test.ts
- mf2/fluent/src/functions.ts
- mf2/icu-messageformat-1/src/functions.ts
- mf2/icu-messageformat-1/src/mf1.test.ts
- mf2/messageformat/src/cst/names.ts
- mf2/messageformat/src/cst/parse-cst.ts
- mf2/messageformat/src/data-model/format-markup.ts
- mf2/messageformat/src/data-model/function-context.ts
- mf2/messageformat/src/data-model/function-ref.test.ts
- mf2/messageformat/src/data-model/literal.test.ts
- mf2/messageformat/src/data-model/markup.test.ts
- mf2/messageformat/src/data-model/parse.ts
- mf2/messageformat/src/data-model/resolve-function-ref.ts
- mf2/messageformat/src/data-model/resolve-value.ts
- mf2/messageformat/src/data-model/resolve-variable.ts
- mf2/messageformat/src/data-model/variable.test.ts
- mf2/messageformat/src/dir-utils.ts
- mf2/messageformat/src/format-context.ts
- mf2/messageformat/src/formatted-parts.ts
- mf2/messageformat/src/functions/datetime.ts
- mf2/messageformat/src/functions/index.ts
- mf2/messageformat/src/functions/number.ts
- mf2/messageformat/src/functions/string.ts
- mf2/messageformat/src/functions/unknown.ts
- mf2/messageformat/src/functions/utils.ts
- mf2/messageformat/src/messageformat.ts
- mf2/messageformat/src/spec.test.ts
- test/utils/mfwg-test-utils.ts
Fixes #431 
Filing initially as a draft, pending on unicode-org/message-format-wg#917 getting merged and the test submodule here updated.
This PR (finally!) adds support for spec-mandated [bidi isolation](https://github.com/unicode-org/message-format-wg/blob/main/spec/formatting.md#handling-bidirectional-text), and uses the _Default Bidi Strategy_ by, well, default. This means that many placeholders will be wrapped with `\u2068...\u2069` FSI/PDI control characters. To disable that, set `bidiIsolation: 'none'` in the formatter options.
No introspection of placeholder contents is included, as doing that right would require implementing the [UAX#9 P2 algorithm](https://www.unicode.org/reports/tr9/#P2) in JavaScript which doesn't really make sense -- when rendering the message contents, the …
> MF2 spec updates: BiDi isolation, u:options

- .github/workflows/docs.yml
- mf2/icu-messageformat-1/README.md
- mf2/icu-messageformat-1/package.json
- mf2/icu-messageformat-1/src/functions.ts
- mf2/icu-messageformat-1/src/index.ts
- mf2/icu-messageformat-1/src/mf1-to-message-data.ts
- mf2/icu-messageformat-1/src/mf1-to-message.ts
- mf2/icu-messageformat-1/src/mf1.test.ts
- mf2/icu-messageformat-1/src/validate.ts
- mf2/messageformat/src/data-model/visit.ts
- mf2/messageformat/src/messageformat.ts
- mf2/messageformat/src/mf2-features.test.ts
- package-lock.json
The accessor `getMF1Functions()` is replaced with a static `MF1Functions`, which contains an expanded set of MF1 compatibility functions; most of these wrap default or draft MF2 spec functions.
A validator `mf1Validate()` is provided. This is not run during `mf1ToMessage()`, though, as the functions now validate their options at runtime (this provides for better fallback).
MF1 syntax support is extended, so datetime & number skeletons + number patterns are now supported. As the MF2 option bags do not provide all of the same features, a best effort is made to match the input. The number format `scale/dddd` token is specifically supported, however, as it's often required for percentage formatting.
> Refactor @messageformat/icu-messageformat-1

- mf2/fluent/README.md
- mf2/fluent/src/fluent-to-resource.ts
- mf2/fluent/src/fluent.test.ts
- mf2/fluent/src/functions.ts
- mf2/messageformat/src/formatted-parts.ts
- mf2/messageformat/src/functions/datetime.ts
- mf2/messageformat/src/functions/number.ts
- mf2/messageformat/src/functions/string.ts
- mf2/messageformat/src/functions/test-functions.ts
- mf2/messageformat/src/functions/unit.ts
- mf2/messageformat/src/functions/unknown.ts
- mf2/messageformat/src/messageformat.ts
- mf2/messageformat/src/mf2-features.test.ts
- mf2/messageformat/src/resolve/format-markup.ts
- mf2/messageformat/src/resolve/function-ref.test.ts
- mf2/messageformat/src/resolve/markup.test.ts
- mf2/messageformat/src/resolve/variable.test.ts
- mf2/messageformat/src/spec.test.ts
- test/utils/mfwg-test-utils.ts
These changes are preparing the project for a final 4.0 release:
- unicode-org/message-format-wg#1050
- unicode-org/message-format-wg#1061
- `@messageformat/fluent`: Add datetime to functions, fix docs example
> MF2 updates

- mf2/fluent/src/fluent-to-message.ts
- mf2/fluent/src/message-to-fluent.ts
- mf2/icu-messageformat-1/src/mf1-to-message-data.ts
- mf2/icu-messageformat-1/src/validate.ts
- mf2/messageformat/src/data-model/from-cst.ts
- mf2/messageformat/src/data-model/parse.ts
- mf2/messageformat/src/data-model/stringify.ts
- mf2/messageformat/src/data-model/types.ts
- mf2/messageformat/src/data-model/visit.ts
- mf2/messageformat/src/resolve/format-markup.ts
- mf2/messageformat/src/resolve/function-context.ts
- mf2/messageformat/src/resolve/resolve-function-ref.ts
- mf2/xliff/src/mf2xliff.ts
- mf2/xliff/src/xliff2mf.ts
Remove the use of `Map` from data-model, to enable using pre-parsed messages. Removing the need for parsing while running my application.
> fix: make the data-model data
